### ISSUE TITLE
MAJORFIX: DOTNET BUILD issue

### ISSUE THREAD

**Issue by cjdutoit** [cjdutoit/Standardly#49]
In VS the project builds and all tests pass

`========== Build: 7 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========`

![image](https://user-images.githubusercontent.com/797750/179405672-52442c00-a27e-4fef-a055-60921ac0a0b0.png)

BUT the DOTNET BUILD command fails which is what we use in the GitHub Actions.  (This can be reproduced locally running DOTNET BUILD in the Package Manager Console)

![image](https://user-images.githubusercontent.com/797750/179405645-3c1887f7-be37-49dd-b6e8-ed4d7f5780ad.png)

**Comment by coeur85** [comment]
i don't think u can use dotnet build with framework 4.8 
can u !

![image](https://user-images.githubusercontent.com/34419909/180802769-01bff69c-8948-45f8-9e7e-e7dc328445ba.png)

**Comment by coeur85** [comment]
i've removed the project from the build, and now it works just fine.
i guess that would be more appropriate because windows only projects (.net framework 4.X) will only be built from inside VS.

![2](https://user-images.githubusercontent.com/34419909/180833309-06b707bf-9271-42aa-a2d4-fcf81cec5034.PNG)
![1](https://user-images.githubusercontent.com/34419909/180833378-e537535f-4c92-4b1b-aad4-b96c57e23017.PNG)
